// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAATheRL5nL5p476udzhtPOYNfGjAI6xWY',
    appId: '1:1020280904386:android:5964ecd32fbab255cbb95b',
    messagingSenderId: '1020280904386',
    projectId: 'fir-9e91b',
    storageBucket: 'fir-9e91b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-mtP6f1qJ9EHBN_94zq9i4NzvGN21awM',
    appId: '1:1020280904386:ios:957d24e50d382f1dcbb95b',
    messagingSenderId: '1020280904386',
    projectId: 'fir-9e91b',
    storageBucket: 'fir-9e91b.appspot.com',
    androidClientId: '1020280904386-5jestih9b4lmuvjrgl2fvrs6sbeim8pv.apps.googleusercontent.com',
    iosClientId: '1020280904386-34a05cpn9787hnb3mcp0hu36d85s1cip.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseStorageFlutter',
  );
}
